return {
	{
		"folke/which-key.nvim",
		event = "VimEnter",
		opts = {
			icons = {
				group = "",
				mappings = vim.g.have_nerd_font,
				keys = vim.g.have_nerd_font and {} or {
					Up = "<Up> ",
					Down = "<Down> ",
					Left = "<Left> ",
					Right = "<Right> ",
					C = "<C-…> ",
					M = "<M-…> ",
					D = "<D-…> ",
					S = "<S-…> ",
					CR = "<CR> ",
					Esc = "<Esc> ",
					ScrollWheelDown = "<ScrollWheelDown> ",
					ScrollWheelUp = "<ScrollWheelUp> ",
					NL = "<NL> ",
					BS = "<BS> ",
					Space = "<Space> ",
					Tab = "<Tab> ",
					F1 = "<F1>",
					F2 = "<F2>",
					F3 = "<F3>",
					F4 = "<F4>",
					F5 = "<F5>",
					F6 = "<F6>",
					F7 = "<F7>",
					F8 = "<F8>",
					F9 = "<F9>",
					F10 = "<F10>",
					F11 = "<F11>",
					F12 = "<F12>",
				},
			},
			spec = {
				{ "<leader>w", group = "[W]indow" },
				{ "<leader>b", group = "[B]uffer" },
				{ "<leader>s", group = "[S]earch" },
				{ "<leader>c", group = "[C]ode", mode = { "n", "x" } },
				{ "<leader>g", group = "[G]it" },
				{ "<leader>q", group = "[Q] Macros" },
				{ "<leader>e", group = "[E]xplorer" },
				{ "<leader>l", group = "[L]aTeX" },
				{ "<leader>t", group = "[T]oggle" },
				{ "<leader>r", group = "[R]ename" },
				{ "<leader>m", group = "[M]arkdown" },
				{ "<leader>h", group = "[H]tml" },
			},
		},
		config = function(_, opts)
			require("which-key").setup(opts)
		end,
	},
}
